### ISSUE TITLE
Min and max in dataSummary will be nan if any elements in the array are nan

### ISSUE THREAD

**Issue by firsttempora** [firsttempora/BEHR-Sonification#2]
The optimal behavior would probably be if they returned nan only if all elements in the array are nan.

Alternately, another approach would be to extend the Array and Array2D classes to override the maxItem, minItem or equivalent methods or add methods nanmaxItem, nanminItem a la Matlab. But that might be more a pain than is worth it right now.

**Comment by ekermit** [comment]
I didn't actually check the behavior.. Does it choose Nan as a min item when there are non-nan elements?

**Comment by firsttempora** [comment]
Yes, min and max seem to be nan when there are any nans in the array, even if there are some non-nan elements (e.g. ~dataSummary[1]["BEHRNO2apriori"]["min"] - you can see just in the column at 0,0 that there are non-nan elements but the summary gives a nan). Mean and median do not seem to be affected - they give nan-nan values.

**Comment by ekermit** [comment]
Alright, I think I might write functions to implement nanmin and nanmax then.. Thats probably cleaner than overriding minItem and maxItem. Its nice that mean and median seem unaffected..
