### ISSUE TITLE
Possible reason for "node not found" error when executing run_trends.scd

### ISSUE THREAD

**Issue by firsttempora** [firsttempora/BEHR-Sonification#3]
I may know why we kept getting node not found errors the first time after rebooting the server. Playing around for something else, it seems like if a `thisProcess.interpreter.executeFile` call that runs a file including SynthDefs and a call to instantiate a synth using one of the definitions are both in a `server.waitForBoot` call, the SynthDefs aren't in place at the time the synth instantiation is executed. Is the `executeFile` call asynchronous or something?

**Comment by ekermit** [comment]
Ah! You're probably right.. We can fix it by adding something like `{0.3.wait;}.defer;` between the sending of the synthdefs and the instantiation of the synths. Basically, sleep the thread long enough for the synthdefs to be compiled

**Comment by firsttempora** [comment]
Fixed with a `defer` call in 4cd313dbab4275575eb4b28f7549461218135f3f
